### ISSUE TITLE
Cloud edit does not want to create new files

### ISSUE THREAD

**Issue by Wendelstein7** [SquidDev-CC/cloud-catcher#11]
I expected I could just type `cloud edit <file>` (where file does not exist yet) to create a new file,
but I found that cloud catcher actually refuses to safe a file that does not exist, showing the following (wrong) error message:

https://media.energetic.pw/plr4g8-f2j.png
( ERROR: <file> could not be saved as it was changed on the remote client. )

Reproduce:
1. initiate a cloud session
2. type `cloud edit nonexistantfilename`
3. enter some text in the file editor in the browser
4. save with CTRL+S
5. witness the faulty error message and the denial of saving

Thanks for fixing in advance!

With love,
~HydroNitrogen

**Comment by SquidDev** [comment]
Fixed in 759bb73c38278dd124eadbb72eecc891f955a1ab. You'll need to re-install `cloud.lua`.
