### ISSUE TITLE
Enter and Backspace not working in terminal in mincraft 1.14+ (maybe 1.13?) 

### ISSUE THREAD

**Issue by sir-maniac** [SquidDev-CC/cloud-catcher#18]
I didn't find any documentation mentioning it, do thought I'd file a bug report.

The remove terminal seems to work just fine, and I can type any letters or numbers, but the backspace and enter keys don't work.  I have tried this on both Chrome v70 and  Firefox v74 on linux.

**Comment by SquidDev** [comment]
Hrmr, that's very odd - I'm unable to reproduce on FF 75 (Windows), but fairly sure I've not had this issue on other versions either. Would you be able to try a couple of things:

 - Does the bug still reproduce on [copy-cat](https://copy-cat.squiddev.cc/)? They use the same underlying web interface, so bugs in one should show up in the other.
 - Can you run the following program `while true do print(os.pullEvent()) end` and screenshot the result of pressing backspace and enter while doing so? Just so I can see if key events are getting incorrectly mapped.

**Comment by sir-maniac** [comment]
Copy-cat does work. 

For the os.pullEvent, the enter and backspace register as different codes.  

minecraft: Enter:257, Backspace:259
In firefox: Enter:28, backspace:14

![image](https://user-images.githubusercontent.com/608494/77465618-8c22c180-6dce-11ea-9942-c36870286566.png)

BTW, the same keycodes show up in copy-cat:
![image](https://user-images.githubusercontent.com/608494/77465849-ed4a9500-6dce-11ea-8631-1bb44f07cadd.png)

**Comment by SquidDev** [comment]
Oh, are you on Minecraft 1.14/1.15 by any chance?

**Comment by sir-maniac** [comment]
> Oh, are you on Minecraft 1.14/1.15 by any chance?

Yes, I'm using 1.15.2

**Comment by SquidDev** [comment]
Fantastic, thanks - Minecraft (and thus CC) changed their key maps in 1.13, but I never thought to handle it in cloud-catcher. Should be an easy enough fix.

**Comment by sir-maniac** [comment]
Just letting you know, I built master locally, and it seems to work fine.  Thanks!

**Comment by SquidDev** [comment]
Fantantic! The website should be all updated too.
