### ISSUE TITLE
Enter, backspace, and a number of other keys not working on 1.12.2

### ISSUE THREAD

**Issue by cynagen** [SquidDev-CC/cloud-catcher#19]
It looks like you pushed through a bugfix for other versions, this has broken Cloud Catcher for SwitchCraft modpack (1.12.2) entirely, can we get a retrofix?

**Comment by cynagen** [comment]
Note: Chrome 80 (64bit)

**Comment by SquidDev** [comment]
Can you redownload cloud.lua and try again?

**Comment by cynagen** [comment]
Working now, thank you!
