### ISSUE TITLE
Fullscreen mode and mobile support

### ISSUE THREAD

**Issue by leveljaap** [SquidDev-CC/cloud-catcher#24]
Hello, I have a suggestion and a possible bug report.

It would be quite nice to be able to use cloud catcher in full screen, as I usually work with large terminals. Also, this isn't very important since I don't do it much, but on mobile mouse events seem to come in wrong. I haven't tested this enough but from what I noticed so far I think they're always coming in at x=1 and y=1. Copy-cat however seems to work fine on mobile.

From Noddle ;p

**Comment by SquidDev** [comment]
I've added full screen in the latest version - currently deploying an update now.

I'm afraid I'm unable to reproduce the issues with mobile - we use the same terminal engine for copy-cat and cloud-catcher, so it _should_ be fine.
