### ISSUE TITLE
Terminal doesn't work in firefox 77.0.1 and 78.0.1

### ISSUE THREAD

**Issue by Lupus590** [SquidDev-CC/cloud-catcher#26]
I also tested in MS edge (the new webkit one I think) and it worked there so it seems to be a FF problem. I checked the javascript consoled an found no errors.

Windows 10 if it was not clear and is needed

**Comment by Lupus590** [comment]
Looks like there is FF update, I'll have another go once I've installed it

**Comment by Lupus590** [comment]
Still broken after the update

**Comment by Lupus590** [comment]
Not sure if this will be useful:
![image](https://user-images.githubusercontent.com/9790321/86501838-c704a000-bd94-11ea-92f2-92b380f49397.png)
turns out there is a console error if you have it open before connecting to the CC computer: 
![image](https://user-images.githubusercontent.com/9790321/86501851-e56a9b80-bd94-11ea-8034-5cea15435350.png)

**Comment by xAnavrins** [comment]
Works fine for me in 78.0.1
I think this might be due to your `term_font.png` file getting a 404 for some reasons, I get a 304 on mine.

![image](https://user-images.githubusercontent.com/5376823/86502852-dcb69d00-bd75-11ea-94cf-1111c136d0a0.png)

**Comment by SquidDev** [comment]
Can you clear your cache? `term_font.png` shouldn't have been loaded by CC for _months_ - it was removed in 7d964241cf2db295cf48bdc59a68bba3efd67ee7, which dates back from January!

This is what I'd expect the network requests to look like:

![image](https://user-images.githubusercontent.com/4346137/86506147-9f2d3080-bdc4-11ea-93b1-9cf6f8c767c6.png)

**Comment by SquidDev** [comment]
Oh, oh, oh. OK, I know why. Go to settings, change the font to "high definition" and then "normal definition" again.

Right, guess I should add some validation to that.

**Comment by Lupus590** [comment]
that fixed it, interestingly the setting was blank
