### ISSUE TITLE
Allow use of alternate shell or start program

### ISSUE THREAD

**Issue by EntityReborn** [SquidDev-CC/cloud-catcher#36]
Instead of invoking shell, allow an override (defaulting to typical shell) so we can launch a different shell at launch. This will help with supporting cloud catcher in startup.lua when using a custom shell.

For example, allow a second argument to the cloud.lua command, specifying a command to run when cloud is connected.

**Comment by SquidDev** [comment]
In the case of custom shells, it's worth noting that you can do `shell.setAlias("shell", "<my custom shell>")` and cc will just use that instead. But agreed a custom program would be good.

**Comment by EntityReborn** [comment]
Changing the alias may have unwanted affects depending on what one is calling, but noted as a workaround

**Comment by SquidDev** [comment]
Fixed in 83609dfe5464c59a018dd937b177abf541880b13.
