### ISSUE TITLE
[BUG] term.getCursorBlink is missing

### ISSUE THREAD

**Issue by Erb3** [SquidDev-CC/cloud-catcher#39]
Hey,

The `term` function called `getCursorBlink` is missing from the cloudcatcher terminal redirect.
Even tho this function is not often used, it is good to have as some GUI frameworks use this function.
A screenshot is provided below:
![image](https://user-images.githubusercontent.com/49862976/179525744-9d068b22-99fe-4d9e-9be3-3348f074b5e3.png)

I don't think there is much more to say.

**Comment by SquidDev** [comment]
Just remembered why this is missing - cloud-catcher predates `getCursorBlink` by 4 months (see https://github.com/dan200/ComputerCraft/pull/577). I have a valid excuse for forgetting it!
