### ISSUE TITLE
Hard-coded localhost on client download

### ISSUE THREAD

**Issue by LostOfThought** [SquidDev-CC/cloud-catcher#47]
https://github.com/SquidDev-CC/cloud-catcher/blob/master/src/host/init.lua#L120

As an end user, the hard-coded `localhost:8080` makes it not a "batteries included" experience.

Would it not be best to have this as a CLI option, either hidden under a `--localhost` or better yet, a `--url`/`--endpoint` option?

**Comment by SquidDev** [comment]
Ahh, it's meant to do so, but looks this was broken in https://github.com/SquidDev-CC/cloud-catcher/commit/2af48afa2055807c6e29981f2e14eeec24308e75.
