### ISSUE TITLE
Issue when using certain characters

### ISSUE THREAD

**Issue by xAnavrins** [SquidDev-CC/cloud-catcher#7]
There seem to be an issue when a character lower than 0x20 (with the exception of 0x0A, 0x0D (LF and CR)) is used with Cloud Catcher.
When they are drawn on the screen, the rendering freezes until it is cleared from the screen, similarly, if contained in a file, the cloud edit command will not be able to open the file.

**Comment by SquidDev** [comment]
Ok, that's really weird. I suspect this is a serialisation issue - I'm afraid I'm on holiday right now, so this'll take a wee bit of time for me to look at.
